[package]
name = "buildpy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
command-run = "1.1.1"
downloader = "0.2.7"
flate2 = "1.0.28"
indicatif = "0.17.8"
simplelog = { version = "^0.12.2", features = ["paris"] }
xshell = "0.2.5"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"

