[package]
name = "buildpy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.2", features = ["derive"] }
downloader = "0.2.7"
flate2 = "1.0.28"
formatx = "0.2.2"
indicatif = "0.17.8"
indicatif-log-bridge = "0.2.2"
log = "0.4.21"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
simplelog = { version = "^0.12.2", features = ["paris"] }
tinytemplate = "1.2.1"
